### ISSUE TITLE
GPU is full

### ISSUE THREAD

**Issue by lixingbao** [LynnHo/DCGAN-LSGAN-WGAN-WGAN-GP-Tensorflow#11]
Hello, when the code runs, the memory is full. What happened? My python version is 3.6, tensorflow version is 1.11, my GPU  is 1080ti, thanks!
the error is as follow:
An error ocurred while starting the kernel
2019󈚥󈚦 08:40:45.229298: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019󈚥󈚦 08:40:45.601632: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:65:00.0
totalMemory: 11.00GiB freeMemory: 9.10GiB
2019󈚥󈚦 08:40:45.603929: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2019󈚥󈚦 08:40:46.556261: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2019󈚥󈚦 08:40:46.558110: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] 0 
2019󈚥󈚦 08:40:46.558407: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0: N 
2019󈚥󈚦 08:40:46.558836: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8789 MB memory) ‑> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:65:00.0, compute capability: 6.1)

**Comment by LynnHo** [comment]
@lixingbao I haven't met such situation before. Besides, I do not see any error in the above log. Can you post more information?

**Comment by lixingbao** [comment]
> @lixingbao I haven't met such situation before. Besides, I do not see any error in the above log. Can you post more information?

ok, thank you for your reply. when code runs, firstly, a warning came out. the warning is as follow.
QueueRunner.__init__(from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use 'tf.data' module
next, for a while, an  error came out. namely,As shown above， An error ocurred while starting the kernel.
Last but not least, can i get your information about version of your python and tensorflow?thank you!

**Comment by lixingbao** [comment]
@LynnHo Ok, thank you for your reply. when code runs, firstly, a warning came out. the warning is as follow.
QueueRunner.init(from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use 'tf.data' module
next, for a while, an error came out. namely,As shown above， An error ocurred while starting the kernel.
Last but not least, can i get your information about version of your python and tensorflow?thank you!

**Comment by LynnHo** [comment]
@lixingbao I cannot find out the cause of the error. But I use lower tf version than yours, I wrote the code by tf1.2.

**Comment by lixingbao** [comment]
Well, thank you very much, if I encounter some difficult issues, I will have to ask you a lot.thank you.

**Comment by JesperChristensen89** [comment]
@LynnHo How much memory would be required to train the largest of the GANs here? Will 8GB 16-bit training always be sufficient?

**Comment by Oldhuntor** [comment]
looks like i have the same issue，my graphic carf is RTX2060 ，cuda version is 9.2.148 and CUDNN version is 7.2：
An error ocurred while starting the kernel
2019󈚩󈚦 17:42:44.123710: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1405] Found device 0 with properties: 
name: GeForce RTX 2060 major: 7 minor: 5 memoryClockRate(GHz): 1.2
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.89GiB
2019󈚩󈚦 17:42:44.125931: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1484] Adding visible gpu devices: 0
2019󈚩󈚦 17:42:47.366346: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019󈚩󈚦 17:42:47.369312: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0 
2019󈚩󈚦 17:42:47.369737: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:984] 0: N 
2019󈚩󈚦 17:42:47.371615: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4644 MB memory) ‑> physical GPU (device: 0, name: GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5)

somebody help me please XD i just brought the new laptop hoping that it can run fast than my old computer which graphic card is 1050ti.
