### ISSUE TITLE
About problem with generating image size

### ISSUE THREAD

**Issue by lixingbao** [LynnHo/DCGAN-LSGAN-WGAN-WGAN-GP-Tensorflow#12]
Hello,can your code only generate 64×64 images? Can I generate an image of the specified size? For example: 256 × 256, if you can, what parameters need to be modified?thank you!

**Comment by LynnHo** [comment]
@lixingbao The architectures of this code are not suitable for 256 images, I think you should use methods for high-resolution image generation such as PGGAN and StyleGAN.

**Comment by lixingbao** [comment]
@LynnHo you mean that Can't this code generate 256×256 images?thanks!

**Comment by LynnHo** [comment]
@lixingbao Yes.

**Comment by lixingbao** [comment]
@LynnHo  Thank you very much,Have you used PGGAN?

**Comment by LynnHo** [comment]
@lixingbao I haven't used PGGAN before.

**Comment by lixingbao** [comment]
@LynnHo  ok, thank you very much!
