### ISSUE TITLE
License

### ISSUE THREAD

**Issue by connellybarnes** [LynnHo/DCGAN-LSGAN-WGAN-WGAN-GP-Tensorflow#2]
Hi Zhenliang He, I wonder whether you would be willing to please license this code under an open source license? If so please add a license, or if not please just close this request. Thanks, Connelly

**Comment by LynnHo** [comment]
@connellybarnes I will add it later. Please feel free to use this code.

**Comment by LynnHo** [comment]
@connellybarnes License is added.
