### ISSUE TITLE
running question

### ISSUE THREAD

**Issue by tuoniaoren** [LynnHo/DCGAN-LSGAN-WGAN-WGAN-GP-Tensorflow#6]
do you meet the program stop without mistakes when the code running for some time ,and the GPU stops work.I changed the value of num_threads。（from 16 to 10）。i run it again.i don't know Is it because the value is too high。

**Comment by LynnHo** [comment]
@tuoniaoren I haven't met your situation before. Maybe it's the machine's problem?

**Comment by tuoniaoren** [comment]
ok!i'll check it out. I'll change the machine
