### ISSUE TITLE
do you try to use Resnet in wgan-gp?

### ISSUE THREAD

**Issue by tuoniaoren** [LynnHo/DCGAN-LSGAN-WGAN-WGAN-GP-Tensorflow#7]
Have you compared the difference between the network structure of DCGAN and the structure of Resnet in WGAN-GP?Is the effect of Resnet will be better than the structure of DCGAN.

**Comment by LynnHo** [comment]
@tuoniaoren I have tried Resnet but it is too slow, so I didn't finish that experiment.

**Comment by tuoniaoren** [comment]
ok,i add inception v3 in the net of D,the result  is better.i will try add more this block
