### ISSUE TITLE
train mnist

### ISSUE THREAD

**Issue by chl916185** [LynnHo/DCGAN-LSGAN-WGAN-WGAN-GP-Tensorflow#8]
[*] Close main session!
 [*] DiskImageData: stop threads and close session!
ｈｏｗ to solve it?
@LynnHo

**Comment by LynnHo** [comment]
@chl916185 Which command did you use? Can you show more information?

**Comment by chl916185** [comment]
Epoch: ( 99) (    4/   10)
Epoch: ( 99) (    5/   10)
Epoch: ( 99) (    6/   10)
Epoch: ( 99) (    7/   10)
Epoch: ( 99) (    8/   10)
Epoch: ( 99) (    9/   10)
Epoch: ( 99) (   10/   10)
Model saved in file: ./checkpoints/cartoon_wgan_gp/Epoch_(99)_(10of10).ckpt
 [*] Close main session!
 [*] DiskImageData: stop threads and close session!
(tensorflow17) chl@chl-System-Produ
@LynnHo

**Comment by LynnHo** [comment]
@chl916185  It just means the training is finished.
